# Generated by Django 4.2 on 2023-04-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='image_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='objects_detected',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='timestamp',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
